theme: minima

nav:
  - title: "Inicio"
    url: "/"
  - title: "Currículum"
    url: "/cv/"
  - title: "Contacto"
    url: "/contacto/"
  - title: "Proyectos"
    url: "/proyectos/"
sass:
  style: compressed

include:
  - assets/css

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

theme: minima

# Añade este:
minima:
  skin: classic
  include_css: false

